[tool.poetry]
name = "fsm-wrapper"
version = "0.1.0"
description = ""
authors = ["DaviidAM <daviid.am28@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
